version: '3.8'
services:
  cas:
    image: creditapprovalsystem:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=CAS.settings
    command: python manage.py runserver 