# Generated by Django 5.2.4 on 2025-07-19 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newcustomerdatamodel',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('monthly_income', models.IntegerField()),
                ('approved_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='loandata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Loan_ID', models.IntegerField()),
                ('Loan_amount', models.IntegerField()),
                ('Tenure', models.IntegerField()),
                ('Interest_rate', models.FloatField()),
                ('EMI', models.IntegerField()),
                ('EMIPOT', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Customer_id', models.ForeignKey(db_column='Customer_id', on_delete=django.db.models.deletion.CASCADE, to='APIs.newcustomerdatamodel')),
            ],
        ),
    ]
