# Generated by Django 5.2.4 on 2025-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newloaneligibility',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('approval', models.BooleanField(default=False)),
                ('Interest_rate', models.FloatField(default=10.0)),
                ('corrected_interest_rate', models.FloatField(default=10.0)),
                ('tenure', models.IntegerField()),
                ('Loan_amount', models.IntegerField()),
                ('monthly_income', models.IntegerField()),
            ],
        ),
    ]
