# Generated by Django 5.2.4 on 2025-07-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_newloaneligibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newloaneligibility',
        ),
    ]
